[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "next dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"